import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/components/Navbar"
import LeftBar from "@/components/components/LeftBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
      <Navbar/>
      <div className="flex flex-row gap-0 bg-[#ffffff]">
        <LeftBar/>
        {children}
      </div>
        </body>
    </html>
  );
}
